"""Record a real run of the system into `frontend/src/data/showcase.json`.

The landing page is public and pre-login, so it has no capture loaded and cannot show live
figures -- which is why it shipped with invented ones (12,482 flows, a 0.87 threat score). This
script produces the honest alternative: an actual run against real CIC-IDS-2018 traffic, frozen
to disk, which the landing page renders as a recorded demo rather than as live telemetry.

Every number in the output came out of the running API. Nothing here is authored by hand.

    # with the API running (python -m uvicorn app.server:app --port 8000)
    python -m scripts.record_showcase
    python -m scripts.record_showcase --rows 200000 --api http://127.0.0.1:8000
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = PROJECT_ROOT / "frontend" / "src" / "data" / "showcase.json"

# A day with real labelled attack traffic. Bot is the family the model handles best on real
# per-host data, so this is the most representative single capture -- but the recorded output
# reports whatever the model actually produces, including any stage it flags as heuristic.
DEFAULT_CAPTURE = PROJECT_ROOT / "data" / "raw" / "flows_real" / "Friday-02-03-2018_TrafficForML_CICFlowMeter.csv"


def _slice_capture(src: Path, rows: int, tmp_dir: Path) -> tuple[Path, dict]:
    df = pd.read_csv(src, nrows=rows, low_memory=False)
    label_mix = {}
    if "Label" in df.columns:
        label_mix = {str(k): int(v) for k, v in df["Label"].value_counts().items()}
    out = tmp_dir / "showcase_capture.csv"
    df.to_csv(out, index=False)
    return out, label_mix


def record(api: str, capture: Path, rows: int) -> dict:
    import tempfile

    tmp_dir = Path(tempfile.mkdtemp(prefix="showcase_"))
    slice_path, label_mix = _slice_capture(capture, rows, tmp_dir)

    with slice_path.open("rb") as fh:
        upload = requests.post(
            f"{api}/api/v1/analysis/upload",
            files={"file": (capture.name, fh, "text/csv")},
            timeout=1800,
        )
    upload.raise_for_status()
    upload_body = upload.json()

    hosts = requests.get(f"{api}/api/v1/forecast/hosts", timeout=120).json()
    if not hosts.get("hosts"):
        raise SystemExit("No hosts scored -- capture too small for a full sequence?")
    host_ip = hosts["hosts"][0]["host_ip"]

    status = requests.get(f"{api}/api/v1/system/status", timeout=60).json()
    predict = requests.post(f"{api}/api/v1/forecast/predict", json={"host_ip": host_ip}, timeout=300).json()
    attribution = requests.post(
        f"{api}/api/v1/explainability/attribution", json={"host_ip": host_ip}, timeout=300
    ).json()
    narrative = requests.get(
        f"{api}/api/v1/attacks/narrative", params={"host_ip": host_ip}, timeout=300
    ).json()
    report = requests.post(f"{api}/api/v1/reports/generate", json={"host_ip": host_ip}, timeout=300).json()
    metrics = requests.get(f"{api}/api/v1/eval/metrics", timeout=60).json()

    return {
        "_comment": (
            "Recorded output of a real run. Generated by scripts/record_showcase.py against the "
            "live API -- do not hand-edit, and do not substitute values. Re-record with: "
            "python -m scripts.record_showcase"
        ),
        "recorded_at": datetime.now(timezone.utc).isoformat(),
        "capture": {
            "file": capture.name,
            "dataset": "CIC-IDS-2018",
            "day": "2 March 2018",
            "rows_read": rows,
            "label_mix": label_mix,
        },
        "upload": upload_body,
        "status": status,
        "hosts": hosts["hosts"],
        "predict": predict,
        "attribution": attribution,
        "narrative": narrative,
        "report": report,
        "metrics": metrics,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--api", default="http://127.0.0.1:8000")
    parser.add_argument("--capture", type=Path, default=DEFAULT_CAPTURE)
    parser.add_argument("--rows", type=int, default=120000)
    args = parser.parse_args()

    if not args.capture.exists():
        raise SystemExit(f"Capture not found: {args.capture}")

    data = record(args.api, args.capture, args.rows)
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(data, indent=1), encoding="utf-8")

    up = data["upload"]
    top = data["hosts"][0]
    print(f"wrote {OUT_PATH.relative_to(PROJECT_ROOT)}")
    print(f"  {up['extracted_flows']:,} flows -> {up['windows']:,} windows -> {up['hosts_scored']} host(s)")
    print(f"  top host {top['host_ip']}: peak {top['peak_prob']} ({top['severity']}), "
          f"{top['current_stage']} -> {top['predicted_stage']}")
    print(f"  ledger entry {data['report']['ledger_index']} hash {data['report']['audit_hash'][:16]}...")


if __name__ == "__main__":
    main()
