"""Incident report as a PDF (pure function: a dict in, PDF bytes out).

A readable one-to-two page document for handing to someone who will not open the dashboard: what was
forecast, the CERT-In reporting position, the plain-language narrative, the recommended first
response, what drove the forecast, and the tamper-evident ledger record it corresponds to.

Deliberately honest about what it is. It is a DRAFT generated by the project, not a certified or
legally filed report -- the same position models/compliance.py and app/server.py already take, and
the header says so on every page.
"""
from __future__ import annotations

import io
from typing import Any
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import KeepTogether, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ORANGE = colors.HexColor("#c2510a")
GREY = colors.HexColor("#555555")
LIGHT = colors.HexColor("#f2f2f2")
AMBER_BG = colors.HexColor("#fff4d6")

DISCLAIMER = (
    "DRAFT -- generated by Phoenix IDPS. This is not a certified compliance document and has not been "
    "filed with CERT-In or any authority. It drafts the report an analyst would review and submit."
)


def _p(text: Any, style: ParagraphStyle) -> Paragraph:
    """Paragraph with every dynamic string XML-escaped: host names and narrative text come from
    capture files and would otherwise be parsed as reportlab markup."""
    return Paragraph(escape(str(text)), style)


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("t", parent=base["Title"], fontSize=18, textColor=ORANGE, alignment=0, spaceAfter=2),
        "sub": ParagraphStyle("s", parent=base["Normal"], fontSize=9, textColor=GREY, spaceAfter=8),
        "h": ParagraphStyle("h", parent=base["Heading2"], fontSize=11.5, textColor=ORANGE, spaceBefore=10, spaceAfter=4),
        "body": ParagraphStyle("b", parent=base["Normal"], fontSize=9.5, leading=13.5),
        "small": ParagraphStyle("sm", parent=base["Normal"], fontSize=8, leading=11, textColor=GREY),
        "mono": ParagraphStyle("m", parent=base["Code"], fontSize=7.4, leading=10),
        "warn": ParagraphStyle("w", parent=base["Normal"], fontSize=8.5, leading=12),
    }


def _table(rows: list[list[Any]], col_widths: list[float], st: dict[str, ParagraphStyle], header: bool = False) -> Table:
    cells = [[_p(c, st["body"]) for c in row] for row in rows]
    t = Table(cells, colWidths=col_widths, hAlign="LEFT")
    style = [
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if header:
        style.append(("BACKGROUND", (0, 0), (-1, 0), LIGHT))
    t.setStyle(TableStyle(style))
    return t


def _footer(canvas, doc) -> None:
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(GREY)
    canvas.drawString(18 * mm, 10 * mm, "DRAFT - not a certified compliance document")
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def build_incident_pdf(data: dict[str, Any]) -> bytes:
    """`data` keys (all read defensively, missing -> "n/a"): host, generated_at, dataset_source,
    peak_prob, peak_stage, horizon_seconds, forecast (list of {seconds, prob, stage, heuristic}),
    compliance ({is_reportable, category, detected_at, reporting_deadline, hours_remaining, text}),
    narrative, recommended_action ({action, detail}), attributions (behavioural list),
    provenance_share_total, provenance_note, ledger ({index, prev_hash, record_hash, intact})."""
    st = _styles()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=18 * mm,
        title=f"Incident report - {data.get('host', 'unknown')}", author="Phoenix IDPS",
    )
    width = A4[0] - 36 * mm
    flow: list[Any] = []

    flow.append(_p("Incident report", st["title"]))
    flow.append(_p(f"Host {data.get('host', 'n/a')}  |  generated {data.get('generated_at', 'n/a')}  |  "
                   f"capture: {data.get('dataset_source', 'n/a')}", st["sub"]))

    warn = Table([[_p(DISCLAIMER, st["warn"])]], colWidths=[width])
    warn.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), AMBER_BG), ("BOX", (0, 0), (-1, -1), 0.6, ORANGE),
                              ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5)]))
    flow.append(warn)

    peak = data.get("peak_prob")
    flow.append(_p("Forecast summary", st["h"]))
    flow.append(_table([
        ["Peak infiltration probability", f"{peak * 100:.1f}%" if isinstance(peak, (int, float)) else "n/a"],
        ["Predicted stage at peak", data.get("peak_stage", "n/a")],
        ["Forecast horizon", f"{data['horizon_seconds']} seconds" if data.get("horizon_seconds") else "n/a"],
    ], [width * 0.45, width * 0.55], st))

    forecast = data.get("forecast") or []
    if forecast:
        rows = [["Step", "Probability", "Predicted stage"]]
        for f in forecast:
            stage = f.get("stage", "n/a") + (" (rule-based)" if f.get("heuristic") else "")
            rows.append([f"t+{f.get('seconds', '?')}s", f"{f.get('prob', 0) * 100:.1f}%", stage])
        flow.append(Spacer(1, 4))
        flow.append(_table(rows, [width * 0.2, width * 0.25, width * 0.55], st, header=True))

    comp = data.get("compliance") or {}
    flow.append(_p("CERT-In reporting position", st["h"]))
    hours = comp.get("hours_remaining")
    flow.append(_table([
        ["Reportable", "Yes" if comp.get("is_reportable") else "No"],
        ["Category", comp.get("category") or "n/a"],
        ["Detected at", comp.get("detected_at", "n/a")],
        ["Reporting deadline (6 h)", comp.get("reporting_deadline", "n/a")],
        ["Time remaining", f"{hours:.1f} h" if isinstance(hours, (int, float))
         else "historical capture -- no live countdown"],
    ], [width * 0.35, width * 0.65], st))

    flow.append(_p("What the model expects", st["h"]))
    flow.append(_p(data.get("narrative") or "n/a", st["body"]))

    action = data.get("recommended_action") or {}
    flow.append(_p("Recommended first response", st["h"]))
    flow.append(_p(action.get("action", "n/a"), st["body"]))
    if action.get("detail"):
        flow.append(_p(action["detail"], st["small"]))

    attrs = data.get("attributions") or []
    prov = data.get("provenance_share_total") or 0
    if attrs or prov >= 0.01:
        # Kept together so the table and its artefact warning never straddle a page break.
        block: list[Any] = [_p("What drove the forecast (gradient x input, top behavioural features)", st["h"])]
        if attrs:
            rows = [["Feature", "Share", "Effect on score"]]
            for a in attrs:
                rows.append([a.get("feature", "?"), f"{a.get('share', 0) * 100:.1f}%", a.get("direction", "?")])
            block.append(_table(rows, [width * 0.5, width * 0.2, width * 0.3], st, header=True))
        if prov >= 0.01:
            block.append(Spacer(1, 4))
            block.append(_p(
                f"Dataset artefact: {prov * 100:.1f}% of this explanation comes from data-provenance flags "
                f"(e.g. has_ip_data). {data.get('provenance_note', '')}", st["small"]))
        flow.append(KeepTogether(block))

    led = data.get("ledger") or {}
    flow.append(_p("Tamper-evident ledger record", st["h"]))
    flow.append(_table([
        ["Record index", led.get("index", "n/a")],
        ["Chain intact", "Yes" if led.get("intact") else ("No" if led.get("intact") is False else "n/a")],
    ], [width * 0.35, width * 0.65], st))
    flow.append(Spacer(1, 3))
    flow.append(_p(f"previous hash: {led.get('prev_hash', 'n/a')}", st["mono"]))
    flow.append(_p(f"record hash:   {led.get('record_hash', 'n/a')}", st["mono"]))

    doc.build(flow, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
